Vagrant.configure("2") do |config|
  
  config.vm.box = 'centos/7'
  config.vm.hostname = 'JenkinsNexus'
  config.vm.network 'forwarded_port', guest: 8080, host: 8080, hostip: '127.0.0.1'
  config.vm.network 'forwarded_port', guest: 8081, host: 8081, hostip: '127.0.0.1'
  config.vm.network "private_network", ip: "192.168.10.5"
  config.vm.provision 'shell', path: 'provision.sh'
  config.vm.provider 'virtualbox' do |v| 
    vb.name = "JenkinsNexus"
    v.memory =3072
  end
  
end
