Vagrant.configure("2") do |config|
  config.vm.box = 'centos/7'
  config.vm.hostname = 'k3s-manager'
  config.vm.network "private_network", ip: "192.168.10.2"
  config.vm.provision 'shell', path: 'provision.sh'
  config.vm.provider 'virtualbox' do |v| 
    vb.name = "k3s-manager"
    v.memory =2048
  end
end
