Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "PrometheusGrafana"
    config.vm.network 'forwarded_port', guest: 9090, host: 9090, hostip: '127.0.0.1'
    config.vm.network 'forwarded_port', guest: 3000, host: 3000, hostip: '127.0.0.1'
    config.vm.network "private_network", ip: "192.168.10.10"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "PrometheusGrafana"
      vb.memory = "2048"
    end
    config.vm.provision "shell", path: "provision.sh"
  end